## 6.1.1 Tensor的数据类型

In [3]:
import torch
a = torch.FloatTensor(2,3)
b = torch.FloatTensor([2,3,4,5])

print(a)
print(b)

tensor([[7.1097e+32, 7.6931e-43, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])
tensor([2., 3., 4., 5.])


In [4]:
import torch
a = torch.IntTensor(2,3)
b = torch.IntTensor([2,3,4,5])
print(a)
print(b)

tensor([[1, 0, 1],
        [0, 1, 0]], dtype=torch.int32)
tensor([2, 3, 4, 5], dtype=torch.int32)


In [5]:
import torch
a = torch.rand(2,3)
print(a)

tensor([[0.5095, 0.6741, 0.5399],
        [0.8854, 0.1369, 0.8524]])


In [6]:
import torch
a = torch.randn(2,3)
print(a)

tensor([[ 0.1311, -0.1023,  1.4568],
        [-1.4879, -0.2263,  0.8310]])


In [7]:
import torch
a = torch.range(1,20,1)
print(a)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20.])


C:\Users\TangJM\AppData\Local\Continuum\anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:2: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  


In [8]:
import torch
a = torch.zeros(2,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 6.1.2 Tensor的运算

In [9]:
import torch
a = torch.randn(2,3)
print(a)

b = torch.abs(a)
print(b)

tensor([[ 0.3989, -0.4934, -0.4506],
        [ 0.6460,  0.2997, -0.8672]])
tensor([[0.3989, 0.4934, 0.4506],
        [0.6460, 0.2997, 0.8672]])


In [10]:
import torch
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.add(a,b)
print(c)

d = torch.randn(2,3)
print(d)

e = torch.add(d,10)
print(e)

tensor([[ 0.0099, -0.2180,  0.1013],
        [-0.4391,  0.4358, -0.9616]])
tensor([[ 0.3734, -0.0415,  1.8486],
        [ 0.9968,  2.0658,  0.9807]])
tensor([[ 0.3833, -0.2594,  1.9499],
        [ 0.5578,  2.5016,  0.0191]])
tensor([[ 0.0508,  1.0536,  1.9926],
        [-1.5132,  0.2732, -1.9060]])
tensor([[10.0508, 11.0536, 11.9926],
        [ 8.4868, 10.2732,  8.0940]])


In [11]:
import torch
a = torch.randn(2,3)
print(a)

b = torch.clamp(a, -0.1, 0.1)
print(b)

tensor([[-0.8499, -0.8785, -0.0690],
        [-0.3499, -0.3421, -0.3021]])
tensor([[-0.1000, -0.1000, -0.0690],
        [-0.1000, -0.1000, -0.1000]])


In [12]:
import torch
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.div(a,b)
print(c)

d = torch.randn(2,3)
print(d)

e = torch.div(d,10)
print(e)

tensor([[-0.3028,  0.3060, -1.9009],
        [-0.5321, -0.8396,  0.2136]])
tensor([[-2.0311, -0.2656, -1.2580],
        [-1.0698, -3.4563,  1.0536]])
tensor([[ 0.1491, -1.1518,  1.5111],
        [ 0.4974,  0.2429,  0.2027]])
tensor([[-1.3703, -3.0902, -0.4144],
        [-1.8607, -0.2151, -1.0270]])
tensor([[-0.1370, -0.3090, -0.0414],
        [-0.1861, -0.0215, -0.1027]])


In [13]:
import torch
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.mul(a,b)
print(c)

d = torch.randn(2,3)
print(d)

e = torch.mul(d,10)
print(e)

tensor([[-0.6717, -0.1676, -1.2317],
        [ 0.6672, -1.5907,  0.2269]])
tensor([[-1.7301,  0.0279,  0.5371],
        [-0.7881,  0.3554, -0.7336]])
tensor([[ 1.1621, -0.0047, -0.6615],
        [-0.5258, -0.5653, -0.1664]])
tensor([[ 0.1351, -0.1300, -0.1726],
        [ 0.3674, -0.9257, -0.9940]])
tensor([[ 1.3514, -1.3001, -1.7264],
        [ 3.6741, -9.2571, -9.9397]])


In [14]:
import torch
a = torch.randn(2,3)
print(a)

b = torch.pow(a, 2)
print(b)

tensor([[-1.9137,  2.0280,  0.3694],
        [-0.6349,  1.2277, -0.7630]])
tensor([[3.6622, 4.1127, 0.1365],
        [0.4031, 1.5073, 0.5822]])


In [15]:
import torch
a = torch.randn(2,3)
print(a)

b = torch.randn(3, 2)
print(b)
c = torch.mm(a, b)
print(c)

tensor([[ 0.6492, -0.0279,  0.7209],
        [ 1.2456,  0.2981, -2.0894]])
tensor([[-1.1380,  0.0607],
        [ 1.1460, -0.1024],
        [-0.1995,  0.9934]])
tensor([[-0.9145,  0.7584],
        [-0.6591, -2.0305]])


In [16]:
import torch
a = torch.randn(2,3)
print(a)

b = torch.randn(3)
print(b)

c = torch.mv(a, b)
print(c)

tensor([[ 0.4910,  1.5749, -1.2206],
        [ 0.8810,  0.6917,  0.8628]])
tensor([ 1.8164,  1.7118, -1.8098])
tensor([5.7969, 1.2227])


## 6.1.3 搭建一个简易神经网络

In [17]:
import torch
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10

x = torch.randn(batch_n, input_data)
y = torch.randn(batch_n, output_data)

w1 = torch.randn(input_data, hidden_layer)
w2 = torch.randn(hidden_layer, output_data)

epoch_n = 20
learning_rate = 1e-6

for epoch in range(epoch_n):
    h1 = x.mm(w1) #100*1000
    h1 = h1.clamp(min = 0)
    y_pred = h1.mm(w2) #100*10
    
    loss = (y_pred - y).pow(2).sum()
    print("Epoch:{}, Loss:{:.4f}".format(epoch,loss))
    
    grad_y_pred = 2*(y_pred - y)
    grad_w2 = h1.t().mm(grad_y_pred)
    
    grad_h = grad_y_pred.clone()
    grad_h = grad_h.mm(w2.t())
    grad_h.clamp_(min=0)
    
    grad_w1 = x.t().mm(grad_h)
    w1 -= learning_rate*grad_w1
w2 -= learning_rate*grad_w2

Epoch:0, Loss:44614652.0000
Epoch:1, Loss:37590700.0000
Epoch:2, Loss:32039814.0000
Epoch:3, Loss:27598886.0000
Epoch:4, Loss:23993762.0000
Epoch:5, Loss:21027476.0000
Epoch:6, Loss:18572716.0000
Epoch:7, Loss:16527320.0000
Epoch:8, Loss:14806139.0000
Epoch:9, Loss:13333976.0000
Epoch:10, Loss:12068554.0000
Epoch:11, Loss:10973207.0000
Epoch:12, Loss:10016574.0000
Epoch:13, Loss:9177390.0000
Epoch:14, Loss:8442720.0000
Epoch:15, Loss:7792887.0000
Epoch:16, Loss:7213850.5000
Epoch:17, Loss:6698411.5000
Epoch:18, Loss:6235929.5000
Epoch:19, Loss:5819661.0000


## 6.2.1 torch.autograd和Variable

In [18]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10

x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

w1 = Variable(torch.randn(input_data, hidden_layer), requires_grad = True)
w2 = Variable(torch.randn(hidden_layer, output_data), requires_grad = True)

epoch_n = 20
learning_rate = 1e-6

for epoch in range(epoch_n):
    y_pred = x.mm(w1).clamp(min = 0).mm(w2)
    loss = (y_pred - y).pow(2).sum()
    print("Epoch:{}, Loss:{:.4f}".format(epoch,loss.data[0]))
    
    loss.backward()
    
    w1.data -= learning_rate*w1.grad.data
    w2.data -= learning_rate*w2.grad.data
    
    w1.grad.data.zero_()
    w2.grad.data.zero_()

C:\Users\TangJM\AppData\Local\Continuum\anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:20: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


Epoch:0, Loss:45073056.0000
Epoch:1, Loss:74175384.0000
Epoch:2, Loss:285344608.0000
Epoch:3, Loss:789865728.0000
Epoch:4, Loss:191025024.0000
Epoch:5, Loss:23417966.0000
Epoch:6, Loss:13452932.0000
Epoch:7, Loss:9015031.0000
Epoch:8, Loss:6529998.5000
Epoch:9, Loss:4968689.0000
Epoch:10, Loss:3915607.0000
Epoch:11, Loss:3164678.5000
Epoch:12, Loss:2609719.7500
Epoch:13, Loss:2187640.0000
Epoch:14, Loss:1859454.1250
Epoch:15, Loss:1599756.7500
Epoch:16, Loss:1390839.0000
Epoch:17, Loss:1220711.1250
Epoch:18, Loss:1080489.8750
Epoch:19, Loss:963833.1250


## 6.2.2 自定义传播函数

In [19]:
import torch
from torch.autograd import Variable
batch_n = 64
hidden_layer = 100
input_data = 1000
output_data = 10

class Model(torch.nn.Module):

    def __init__(self):
        super(Model, self).__init__()
    
    def forward(self, input, w1, w2):
        x = torch.mm(input, w1)
        x = torch.clamp(x, min = 0)
        x =torch.mm(x, w2)
        return x
    
    def backward(self):
        pass
    
model = Model()


x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

w1 = Variable(torch.randn(input_data, hidden_layer), requires_grad = True)
w2 = Variable(torch.randn(hidden_layer, output_data) ,requires_grad = True)

epoch_n = 30
learning_rate = 1e-6

for epoch in range(epoch_n):
    y_pred = model(x, w1, w2)
    
    loss = (y_pred - y).pow(2).sum()
    print("Epoch:{}, Loss:{:.4f}".format(epoch,loss.data[0]))
    loss.backward()
    
    w1.data -= learning_rate * w1.grad.data
    w2.data -= learning_rate * w2.grad.data
    
    w1.grad.data.zero_()
    w2.grad.data.zero_()

Epoch:0, Loss:28788926.0000
Epoch:1, Loss:21308552.0000
Epoch:2, Loss:17491036.0000
Epoch:3, Loss:14828819.0000
Epoch:4, Loss:12308512.0000
Epoch:5, Loss:9833089.0000
Epoch:6, Loss:7489211.0000
Epoch:7, Loss:5521263.0000
Epoch:8, Loss:3978119.2500
Epoch:9, Loss:2858498.7500
Epoch:10, Loss:2070783.1250
Epoch:11, Loss:1530376.8750
Epoch:12, Loss:1158310.2500
Epoch:13, Loss:900517.8750
Epoch:14, Loss:717804.2500
Epoch:15, Loss:585185.5625
Epoch:16, Loss:485953.3125
Epoch:17, Loss:409662.6875
Epoch:18, Loss:349590.1875
Epoch:19, Loss:301136.5625
Epoch:20, Loss:261390.5312
Epoch:21, Loss:228276.8906
Epoch:22, Loss:200343.7656
Epoch:23, Loss:176528.1562
Epoch:24, Loss:156090.5938
Epoch:25, Loss:138447.9688
Epoch:26, Loss:123131.2969
Epoch:27, Loss:109789.3750
Epoch:28, Loss:98106.7578
Epoch:29, Loss:87844.6641


C:\Users\TangJM\AppData\Local\Continuum\anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:38: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


## 6.3.1 PyTorch之torch.nn

In [20]:
hidden_layer = 100
input_data = 1000
output_data = 10
models = torch.nn.Sequential(
torch.nn.Linear(input_data, hidden_layer),
torch.nn.ReLU(),
torch.nn.Linear(hidden_layer, output_data)
)
print(models)

Sequential(
  (0): Linear(in_features=1000, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=10, bias=True)
)


In [21]:
hidden_layer = 100
input_data = 1000
output_data = 10
from collections import OrderedDict
models = torch.nn.Sequential(OrderedDict([
("Line1",torch.nn.Linear(input_data, hidden_layer)),
("Relu1",torch.nn.ReLU()),
("Line2",torch.nn.Linear(hidden_layer, output_data))])
)
print(models)

Sequential(
  (Line1): Linear(in_features=1000, out_features=100, bias=True)
  (Relu1): ReLU()
  (Line2): Linear(in_features=100, out_features=10, bias=True)
)


In [23]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.MSELoss()
x = Variable(torch.randn(100,100))
y = Variable(torch.randn(100,100))
loss = loss_f(x,y)
print(loss.data)

tensor(1.9532)


In [24]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.L1Loss()
x = Variable(torch.randn(100,100))
y = Variable(torch.randn(100,100))
loss = loss_f(x,y)
print(loss.data)

tensor(1.1165)


In [25]:
import torch
from torch.autograd import Variable
loss_f = torch.nn.CrossEntropyLoss()
x = Variable(torch.randn(3, 5))
y = Variable(torch.LongTensor(3).random_(5))
loss = loss_f(x,y)
print(loss.data)

tensor(1.7071)


In [28]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10
x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad = False)

models = torch.nn.Sequential(
torch.nn.Linear(input_data, hidden_layer),
torch.nn.ReLU(),
torch.nn.Linear(hidden_layer, output_data)
)

epoch_n = 10000
learning_rate = 1e-4
loss_fn = torch.nn.MSELoss()

for epoch in range(epoch_n):
    y_pred = models(x)
    loss = loss_fn(y_pred, y)
    if epoch%1000 == 0:
        print("Epoch:{}, Loss:{:.4f}".format(epoch,loss.data[0]))
    models.zero_grad()
    loss.backward()
    for param in models.parameters():
        param.data -= param.grad.data*learning_rate

C:\Users\TangJM\AppData\Local\Continuum\anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:24: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


Epoch:0, Loss:1.0791
Epoch:1000, Loss:0.9969
Epoch:2000, Loss:0.9262
Epoch:3000, Loss:0.8644
Epoch:4000, Loss:0.8096
Epoch:5000, Loss:0.7604
Epoch:6000, Loss:0.7155
Epoch:7000, Loss:0.6743
Epoch:8000, Loss:0.6364
Epoch:9000, Loss:0.6009


## 6.3.2 PyTorch之torch.optim

In [29]:
import torch
from torch.autograd import Variable
batch_n = 100
hidden_layer = 100
input_data = 1000
output_data = 10

x = Variable(torch.randn(batch_n, input_data), requires_grad = False)
y = Variable(torch.randn(batch_n, output_data), requires_grad=False)

models = torch.nn.Sequential(
torch.nn.Linear(input_data, hidden_layer),
torch.nn.ReLU(),
torch.nn.Linear(hidden_layer, output_data)
)

epoch_n = 10000
learning_rate = 1e-4
loss_fn = torch.nn.MSELoss()

optimzer = torch.optim.Adam(models.parameters(), lr = learning_rate)

for epoch in range(epoch_n):
    y_pred = models(x)
    loss = loss_fn(y_pred, y)
    print("Epoch:{}, Loss:{:.4f}".format(epoch,loss.data[0]))
    optimzer.zero_grad()
    
    loss.backward()
    optimzer.step()

C:\Users\TangJM\AppData\Local\Continuum\anaconda3\envs\ml\lib\site-packages\ipykernel_launcher.py:26: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


Epoch:0, Loss:1.0183
Epoch:1, Loss:0.9978
Epoch:2, Loss:0.9777
Epoch:3, Loss:0.9581
Epoch:4, Loss:0.9390
Epoch:5, Loss:0.9203
Epoch:6, Loss:0.9020
Epoch:7, Loss:0.8842
Epoch:8, Loss:0.8670
Epoch:9, Loss:0.8501
Epoch:10, Loss:0.8336
Epoch:11, Loss:0.8174
Epoch:12, Loss:0.8017
Epoch:13, Loss:0.7862
Epoch:14, Loss:0.7712
Epoch:15, Loss:0.7565
Epoch:16, Loss:0.7421
Epoch:17, Loss:0.7281
Epoch:18, Loss:0.7143
Epoch:19, Loss:0.7009
Epoch:20, Loss:0.6878
Epoch:21, Loss:0.6750
Epoch:22, Loss:0.6624
Epoch:23, Loss:0.6500
Epoch:24, Loss:0.6380
Epoch:25, Loss:0.6262
Epoch:26, Loss:0.6145
Epoch:27, Loss:0.6031
Epoch:28, Loss:0.5919
Epoch:29, Loss:0.5809
Epoch:30, Loss:0.5701
Epoch:31, Loss:0.5596
Epoch:32, Loss:0.5492
Epoch:33, Loss:0.5391
Epoch:34, Loss:0.5291
Epoch:35, Loss:0.5194
Epoch:36, Loss:0.5098
Epoch:37, Loss:0.5004
Epoch:38, Loss:0.4911
Epoch:39, Loss:0.4820
Epoch:40, Loss:0.4730
Epoch:41, Loss:0.4642
Epoch:42, Loss:0.4556
Epoch:43, Loss:0.4471
Epoch:44, Loss:0.4387
Epoch:45, Loss:0.430

Epoch:439, Loss:0.0000
Epoch:440, Loss:0.0000
Epoch:441, Loss:0.0000
Epoch:442, Loss:0.0000
Epoch:443, Loss:0.0000
Epoch:444, Loss:0.0000
Epoch:445, Loss:0.0000
Epoch:446, Loss:0.0000
Epoch:447, Loss:0.0000
Epoch:448, Loss:0.0000
Epoch:449, Loss:0.0000
Epoch:450, Loss:0.0000
Epoch:451, Loss:0.0000
Epoch:452, Loss:0.0000
Epoch:453, Loss:0.0000
Epoch:454, Loss:0.0000
Epoch:455, Loss:0.0000
Epoch:456, Loss:0.0000
Epoch:457, Loss:0.0000
Epoch:458, Loss:0.0000
Epoch:459, Loss:0.0000
Epoch:460, Loss:0.0000
Epoch:461, Loss:0.0000
Epoch:462, Loss:0.0000
Epoch:463, Loss:0.0000
Epoch:464, Loss:0.0000
Epoch:465, Loss:0.0000
Epoch:466, Loss:0.0000
Epoch:467, Loss:0.0000
Epoch:468, Loss:0.0000
Epoch:469, Loss:0.0000
Epoch:470, Loss:0.0000
Epoch:471, Loss:0.0000
Epoch:472, Loss:0.0000
Epoch:473, Loss:0.0000
Epoch:474, Loss:0.0000
Epoch:475, Loss:0.0000
Epoch:476, Loss:0.0000
Epoch:477, Loss:0.0000
Epoch:478, Loss:0.0000
Epoch:479, Loss:0.0000
Epoch:480, Loss:0.0000
Epoch:481, Loss:0.0000
Epoch:482, 

Epoch:845, Loss:0.0000
Epoch:846, Loss:0.0000
Epoch:847, Loss:0.0000
Epoch:848, Loss:0.0000
Epoch:849, Loss:0.0000
Epoch:850, Loss:0.0000
Epoch:851, Loss:0.0000
Epoch:852, Loss:0.0000
Epoch:853, Loss:0.0000
Epoch:854, Loss:0.0000
Epoch:855, Loss:0.0000
Epoch:856, Loss:0.0000
Epoch:857, Loss:0.0000
Epoch:858, Loss:0.0000
Epoch:859, Loss:0.0000
Epoch:860, Loss:0.0000
Epoch:861, Loss:0.0000
Epoch:862, Loss:0.0000
Epoch:863, Loss:0.0000
Epoch:864, Loss:0.0000
Epoch:865, Loss:0.0000
Epoch:866, Loss:0.0000
Epoch:867, Loss:0.0000
Epoch:868, Loss:0.0000
Epoch:869, Loss:0.0000
Epoch:870, Loss:0.0000
Epoch:871, Loss:0.0000
Epoch:872, Loss:0.0000
Epoch:873, Loss:0.0000
Epoch:874, Loss:0.0000
Epoch:875, Loss:0.0000
Epoch:876, Loss:0.0000
Epoch:877, Loss:0.0000
Epoch:878, Loss:0.0000
Epoch:879, Loss:0.0000
Epoch:880, Loss:0.0000
Epoch:881, Loss:0.0000
Epoch:882, Loss:0.0000
Epoch:883, Loss:0.0000
Epoch:884, Loss:0.0000
Epoch:885, Loss:0.0000
Epoch:886, Loss:0.0000
Epoch:887, Loss:0.0000
Epoch:888, 

Epoch:1283, Loss:0.0000
Epoch:1284, Loss:0.0000
Epoch:1285, Loss:0.0000
Epoch:1286, Loss:0.0000
Epoch:1287, Loss:0.0000
Epoch:1288, Loss:0.0000
Epoch:1289, Loss:0.0000
Epoch:1290, Loss:0.0000
Epoch:1291, Loss:0.0000
Epoch:1292, Loss:0.0000
Epoch:1293, Loss:0.0000
Epoch:1294, Loss:0.0000
Epoch:1295, Loss:0.0000
Epoch:1296, Loss:0.0000
Epoch:1297, Loss:0.0000
Epoch:1298, Loss:0.0000
Epoch:1299, Loss:0.0000
Epoch:1300, Loss:0.0000
Epoch:1301, Loss:0.0000
Epoch:1302, Loss:0.0000
Epoch:1303, Loss:0.0000
Epoch:1304, Loss:0.0000
Epoch:1305, Loss:0.0000
Epoch:1306, Loss:0.0000
Epoch:1307, Loss:0.0000
Epoch:1308, Loss:0.0000
Epoch:1309, Loss:0.0000
Epoch:1310, Loss:0.0000
Epoch:1311, Loss:0.0000
Epoch:1312, Loss:0.0000
Epoch:1313, Loss:0.0000
Epoch:1314, Loss:0.0000
Epoch:1315, Loss:0.0000
Epoch:1316, Loss:0.0000
Epoch:1317, Loss:0.0000
Epoch:1318, Loss:0.0000
Epoch:1319, Loss:0.0000
Epoch:1320, Loss:0.0000
Epoch:1321, Loss:0.0000
Epoch:1322, Loss:0.0000
Epoch:1323, Loss:0.0000
Epoch:1324, Loss

Epoch:1626, Loss:0.0000
Epoch:1627, Loss:0.0000
Epoch:1628, Loss:0.0000
Epoch:1629, Loss:0.0000
Epoch:1630, Loss:0.0000
Epoch:1631, Loss:0.0000
Epoch:1632, Loss:0.0000
Epoch:1633, Loss:0.0000
Epoch:1634, Loss:0.0000
Epoch:1635, Loss:0.0000
Epoch:1636, Loss:0.0000
Epoch:1637, Loss:0.0000
Epoch:1638, Loss:0.0000
Epoch:1639, Loss:0.0000
Epoch:1640, Loss:0.0000
Epoch:1641, Loss:0.0000
Epoch:1642, Loss:0.0000
Epoch:1643, Loss:0.0000
Epoch:1644, Loss:0.0000
Epoch:1645, Loss:0.0000
Epoch:1646, Loss:0.0000
Epoch:1647, Loss:0.0000
Epoch:1648, Loss:0.0000
Epoch:1649, Loss:0.0000
Epoch:1650, Loss:0.0000
Epoch:1651, Loss:0.0000
Epoch:1652, Loss:0.0000
Epoch:1653, Loss:0.0000
Epoch:1654, Loss:0.0000
Epoch:1655, Loss:0.0000
Epoch:1656, Loss:0.0000
Epoch:1657, Loss:0.0000
Epoch:1658, Loss:0.0000
Epoch:1659, Loss:0.0000
Epoch:1660, Loss:0.0000
Epoch:1661, Loss:0.0000
Epoch:1662, Loss:0.0000
Epoch:1663, Loss:0.0000
Epoch:1664, Loss:0.0000
Epoch:1665, Loss:0.0000
Epoch:1666, Loss:0.0000
Epoch:1667, Loss

Epoch:2081, Loss:0.0000
Epoch:2082, Loss:0.0000
Epoch:2083, Loss:0.0000
Epoch:2084, Loss:0.0000
Epoch:2085, Loss:0.0000
Epoch:2086, Loss:0.0000
Epoch:2087, Loss:0.0000
Epoch:2088, Loss:0.0000
Epoch:2089, Loss:0.0000
Epoch:2090, Loss:0.0000
Epoch:2091, Loss:0.0000
Epoch:2092, Loss:0.0000
Epoch:2093, Loss:0.0000
Epoch:2094, Loss:0.0000
Epoch:2095, Loss:0.0000
Epoch:2096, Loss:0.0000
Epoch:2097, Loss:0.0000
Epoch:2098, Loss:0.0000
Epoch:2099, Loss:0.0000
Epoch:2100, Loss:0.0000
Epoch:2101, Loss:0.0000
Epoch:2102, Loss:0.0000
Epoch:2103, Loss:0.0000
Epoch:2104, Loss:0.0000
Epoch:2105, Loss:0.0000
Epoch:2106, Loss:0.0000
Epoch:2107, Loss:0.0000
Epoch:2108, Loss:0.0000
Epoch:2109, Loss:0.0000
Epoch:2110, Loss:0.0000
Epoch:2111, Loss:0.0000
Epoch:2112, Loss:0.0000
Epoch:2113, Loss:0.0000
Epoch:2114, Loss:0.0000
Epoch:2115, Loss:0.0000
Epoch:2116, Loss:0.0000
Epoch:2117, Loss:0.0000
Epoch:2118, Loss:0.0000
Epoch:2119, Loss:0.0000
Epoch:2120, Loss:0.0000
Epoch:2121, Loss:0.0000
Epoch:2122, Loss

Epoch:2517, Loss:0.0000
Epoch:2518, Loss:0.0000
Epoch:2519, Loss:0.0000
Epoch:2520, Loss:0.0000
Epoch:2521, Loss:0.0000
Epoch:2522, Loss:0.0000
Epoch:2523, Loss:0.0000
Epoch:2524, Loss:0.0000
Epoch:2525, Loss:0.0000
Epoch:2526, Loss:0.0000
Epoch:2527, Loss:0.0000
Epoch:2528, Loss:0.0000
Epoch:2529, Loss:0.0000
Epoch:2530, Loss:0.0000
Epoch:2531, Loss:0.0000
Epoch:2532, Loss:0.0000
Epoch:2533, Loss:0.0000
Epoch:2534, Loss:0.0000
Epoch:2535, Loss:0.0000
Epoch:2536, Loss:0.0000
Epoch:2537, Loss:0.0000
Epoch:2538, Loss:0.0000
Epoch:2539, Loss:0.0000
Epoch:2540, Loss:0.0000
Epoch:2541, Loss:0.0000
Epoch:2542, Loss:0.0000
Epoch:2543, Loss:0.0000
Epoch:2544, Loss:0.0000
Epoch:2545, Loss:0.0000
Epoch:2546, Loss:0.0000
Epoch:2547, Loss:0.0000
Epoch:2548, Loss:0.0000
Epoch:2549, Loss:0.0000
Epoch:2550, Loss:0.0000
Epoch:2551, Loss:0.0000
Epoch:2552, Loss:0.0000
Epoch:2553, Loss:0.0000
Epoch:2554, Loss:0.0000
Epoch:2555, Loss:0.0000
Epoch:2556, Loss:0.0000
Epoch:2557, Loss:0.0000
Epoch:2558, Loss

Epoch:2930, Loss:0.0000
Epoch:2931, Loss:0.0000
Epoch:2932, Loss:0.0000
Epoch:2933, Loss:0.0000
Epoch:2934, Loss:0.0000
Epoch:2935, Loss:0.0000
Epoch:2936, Loss:0.0000
Epoch:2937, Loss:0.0000
Epoch:2938, Loss:0.0000
Epoch:2939, Loss:0.0000
Epoch:2940, Loss:0.0000
Epoch:2941, Loss:0.0000
Epoch:2942, Loss:0.0000
Epoch:2943, Loss:0.0000
Epoch:2944, Loss:0.0000
Epoch:2945, Loss:0.0000
Epoch:2946, Loss:0.0000
Epoch:2947, Loss:0.0000
Epoch:2948, Loss:0.0000
Epoch:2949, Loss:0.0000
Epoch:2950, Loss:0.0000
Epoch:2951, Loss:0.0000
Epoch:2952, Loss:0.0000
Epoch:2953, Loss:0.0000
Epoch:2954, Loss:0.0000
Epoch:2955, Loss:0.0000
Epoch:2956, Loss:0.0000
Epoch:2957, Loss:0.0000
Epoch:2958, Loss:0.0000
Epoch:2959, Loss:0.0000
Epoch:2960, Loss:0.0000
Epoch:2961, Loss:0.0000
Epoch:2962, Loss:0.0000
Epoch:2963, Loss:0.0000
Epoch:2964, Loss:0.0000
Epoch:2965, Loss:0.0000
Epoch:2966, Loss:0.0000
Epoch:2967, Loss:0.0000
Epoch:2968, Loss:0.0000
Epoch:2969, Loss:0.0000
Epoch:2970, Loss:0.0000
Epoch:2971, Loss

Epoch:3333, Loss:0.0000
Epoch:3334, Loss:0.0000
Epoch:3335, Loss:0.0000
Epoch:3336, Loss:0.0000
Epoch:3337, Loss:0.0000
Epoch:3338, Loss:0.0000
Epoch:3339, Loss:0.0000
Epoch:3340, Loss:0.0000
Epoch:3341, Loss:0.0000
Epoch:3342, Loss:0.0000
Epoch:3343, Loss:0.0000
Epoch:3344, Loss:0.0000
Epoch:3345, Loss:0.0000
Epoch:3346, Loss:0.0000
Epoch:3347, Loss:0.0000
Epoch:3348, Loss:0.0000
Epoch:3349, Loss:0.0000
Epoch:3350, Loss:0.0000
Epoch:3351, Loss:0.0000
Epoch:3352, Loss:0.0000
Epoch:3353, Loss:0.0000
Epoch:3354, Loss:0.0000
Epoch:3355, Loss:0.0000
Epoch:3356, Loss:0.0000
Epoch:3357, Loss:0.0000
Epoch:3358, Loss:0.0000
Epoch:3359, Loss:0.0000
Epoch:3360, Loss:0.0000
Epoch:3361, Loss:0.0000
Epoch:3362, Loss:0.0000
Epoch:3363, Loss:0.0000
Epoch:3364, Loss:0.0000
Epoch:3365, Loss:0.0000
Epoch:3366, Loss:0.0000
Epoch:3367, Loss:0.0000
Epoch:3368, Loss:0.0000
Epoch:3369, Loss:0.0000
Epoch:3370, Loss:0.0000
Epoch:3371, Loss:0.0000
Epoch:3372, Loss:0.0000
Epoch:3373, Loss:0.0000
Epoch:3374, Loss

Epoch:3744, Loss:0.0000
Epoch:3745, Loss:0.0000
Epoch:3746, Loss:0.0000
Epoch:3747, Loss:0.0000
Epoch:3748, Loss:0.0000
Epoch:3749, Loss:0.0000
Epoch:3750, Loss:0.0000
Epoch:3751, Loss:0.0000
Epoch:3752, Loss:0.0000
Epoch:3753, Loss:0.0000
Epoch:3754, Loss:0.0000
Epoch:3755, Loss:0.0000
Epoch:3756, Loss:0.0000
Epoch:3757, Loss:0.0000
Epoch:3758, Loss:0.0000
Epoch:3759, Loss:0.0000
Epoch:3760, Loss:0.0000
Epoch:3761, Loss:0.0000
Epoch:3762, Loss:0.0000
Epoch:3763, Loss:0.0000
Epoch:3764, Loss:0.0000
Epoch:3765, Loss:0.0000
Epoch:3766, Loss:0.0000
Epoch:3767, Loss:0.0000
Epoch:3768, Loss:0.0000
Epoch:3769, Loss:0.0000
Epoch:3770, Loss:0.0000
Epoch:3771, Loss:0.0000
Epoch:3772, Loss:0.0000
Epoch:3773, Loss:0.0000
Epoch:3774, Loss:0.0000
Epoch:3775, Loss:0.0000
Epoch:3776, Loss:0.0000
Epoch:3777, Loss:0.0000
Epoch:3778, Loss:0.0000
Epoch:3779, Loss:0.0000
Epoch:3780, Loss:0.0000
Epoch:3781, Loss:0.0000
Epoch:3782, Loss:0.0000
Epoch:3783, Loss:0.0000
Epoch:3784, Loss:0.0000
Epoch:3785, Loss

Epoch:4161, Loss:0.0000
Epoch:4162, Loss:0.0000
Epoch:4163, Loss:0.0000
Epoch:4164, Loss:0.0000
Epoch:4165, Loss:0.0000
Epoch:4166, Loss:0.0000
Epoch:4167, Loss:0.0000
Epoch:4168, Loss:0.0000
Epoch:4169, Loss:0.0000
Epoch:4170, Loss:0.0000
Epoch:4171, Loss:0.0000
Epoch:4172, Loss:0.0000
Epoch:4173, Loss:0.0000
Epoch:4174, Loss:0.0000
Epoch:4175, Loss:0.0000
Epoch:4176, Loss:0.0000
Epoch:4177, Loss:0.0000
Epoch:4178, Loss:0.0000
Epoch:4179, Loss:0.0000
Epoch:4180, Loss:0.0000
Epoch:4181, Loss:0.0000
Epoch:4182, Loss:0.0000
Epoch:4183, Loss:0.0000
Epoch:4184, Loss:0.0000
Epoch:4185, Loss:0.0000
Epoch:4186, Loss:0.0000
Epoch:4187, Loss:0.0000
Epoch:4188, Loss:0.0000
Epoch:4189, Loss:0.0000
Epoch:4190, Loss:0.0000
Epoch:4191, Loss:0.0000
Epoch:4192, Loss:0.0000
Epoch:4193, Loss:0.0000
Epoch:4194, Loss:0.0000
Epoch:4195, Loss:0.0000
Epoch:4196, Loss:0.0000
Epoch:4197, Loss:0.0000
Epoch:4198, Loss:0.0000
Epoch:4199, Loss:0.0000
Epoch:4200, Loss:0.0000
Epoch:4201, Loss:0.0000
Epoch:4202, Loss

Epoch:4570, Loss:0.0000
Epoch:4571, Loss:0.0000
Epoch:4572, Loss:0.0000
Epoch:4573, Loss:0.0000
Epoch:4574, Loss:0.0000
Epoch:4575, Loss:0.0000
Epoch:4576, Loss:0.0000
Epoch:4577, Loss:0.0000
Epoch:4578, Loss:0.0000
Epoch:4579, Loss:0.0000
Epoch:4580, Loss:0.0000
Epoch:4581, Loss:0.0000
Epoch:4582, Loss:0.0000
Epoch:4583, Loss:0.0000
Epoch:4584, Loss:0.0000
Epoch:4585, Loss:0.0000
Epoch:4586, Loss:0.0000
Epoch:4587, Loss:0.0000
Epoch:4588, Loss:0.0000
Epoch:4589, Loss:0.0000
Epoch:4590, Loss:0.0000
Epoch:4591, Loss:0.0000
Epoch:4592, Loss:0.0000
Epoch:4593, Loss:0.0000
Epoch:4594, Loss:0.0000
Epoch:4595, Loss:0.0000
Epoch:4596, Loss:0.0000
Epoch:4597, Loss:0.0000
Epoch:4598, Loss:0.0000
Epoch:4599, Loss:0.0000
Epoch:4600, Loss:0.0000
Epoch:4601, Loss:0.0000
Epoch:4602, Loss:0.0000
Epoch:4603, Loss:0.0000
Epoch:4604, Loss:0.0000
Epoch:4605, Loss:0.0000
Epoch:4606, Loss:0.0000
Epoch:4607, Loss:0.0000
Epoch:4608, Loss:0.0000
Epoch:4609, Loss:0.0000
Epoch:4610, Loss:0.0000
Epoch:4611, Loss

Epoch:4912, Loss:0.0000
Epoch:4913, Loss:0.0000
Epoch:4914, Loss:0.0000
Epoch:4915, Loss:0.0000
Epoch:4916, Loss:0.0000
Epoch:4917, Loss:0.0000
Epoch:4918, Loss:0.0000
Epoch:4919, Loss:0.0000
Epoch:4920, Loss:0.0000
Epoch:4921, Loss:0.0000
Epoch:4922, Loss:0.0000
Epoch:4923, Loss:0.0000
Epoch:4924, Loss:0.0000
Epoch:4925, Loss:0.0000
Epoch:4926, Loss:0.0000
Epoch:4927, Loss:0.0000
Epoch:4928, Loss:0.0000
Epoch:4929, Loss:0.0000
Epoch:4930, Loss:0.0000
Epoch:4931, Loss:0.0000
Epoch:4932, Loss:0.0000
Epoch:4933, Loss:0.0000
Epoch:4934, Loss:0.0000
Epoch:4935, Loss:0.0000
Epoch:4936, Loss:0.0000
Epoch:4937, Loss:0.0000
Epoch:4938, Loss:0.0000
Epoch:4939, Loss:0.0000
Epoch:4940, Loss:0.0000
Epoch:4941, Loss:0.0000
Epoch:4942, Loss:0.0000
Epoch:4943, Loss:0.0000
Epoch:4944, Loss:0.0000
Epoch:4945, Loss:0.0000
Epoch:4946, Loss:0.0000
Epoch:4947, Loss:0.0000
Epoch:4948, Loss:0.0000
Epoch:4949, Loss:0.0000
Epoch:4950, Loss:0.0000
Epoch:4951, Loss:0.0000
Epoch:4952, Loss:0.0000
Epoch:4953, Loss

Epoch:5253, Loss:0.0000
Epoch:5254, Loss:0.0000
Epoch:5255, Loss:0.0000
Epoch:5256, Loss:0.0000
Epoch:5257, Loss:0.0000
Epoch:5258, Loss:0.0000
Epoch:5259, Loss:0.0000
Epoch:5260, Loss:0.0000
Epoch:5261, Loss:0.0000
Epoch:5262, Loss:0.0000
Epoch:5263, Loss:0.0000
Epoch:5264, Loss:0.0000
Epoch:5265, Loss:0.0000
Epoch:5266, Loss:0.0000
Epoch:5267, Loss:0.0000
Epoch:5268, Loss:0.0000
Epoch:5269, Loss:0.0000
Epoch:5270, Loss:0.0000
Epoch:5271, Loss:0.0000
Epoch:5272, Loss:0.0000
Epoch:5273, Loss:0.0000
Epoch:5274, Loss:0.0000
Epoch:5275, Loss:0.0000
Epoch:5276, Loss:0.0000
Epoch:5277, Loss:0.0000
Epoch:5278, Loss:0.0000
Epoch:5279, Loss:0.0000
Epoch:5280, Loss:0.0000
Epoch:5281, Loss:0.0000
Epoch:5282, Loss:0.0000
Epoch:5283, Loss:0.0000
Epoch:5284, Loss:0.0000
Epoch:5285, Loss:0.0000
Epoch:5286, Loss:0.0000
Epoch:5287, Loss:0.0000
Epoch:5288, Loss:0.0000
Epoch:5289, Loss:0.0000
Epoch:5290, Loss:0.0000
Epoch:5291, Loss:0.0000
Epoch:5292, Loss:0.0000
Epoch:5293, Loss:0.0000
Epoch:5294, Loss

Epoch:5665, Loss:0.0000
Epoch:5666, Loss:0.0000
Epoch:5667, Loss:0.0000
Epoch:5668, Loss:0.0000
Epoch:5669, Loss:0.0000
Epoch:5670, Loss:0.0000
Epoch:5671, Loss:0.0000
Epoch:5672, Loss:0.0000
Epoch:5673, Loss:0.0000
Epoch:5674, Loss:0.0000
Epoch:5675, Loss:0.0000
Epoch:5676, Loss:0.0000
Epoch:5677, Loss:0.0000
Epoch:5678, Loss:0.0000
Epoch:5679, Loss:0.0000
Epoch:5680, Loss:0.0000
Epoch:5681, Loss:0.0000
Epoch:5682, Loss:0.0000
Epoch:5683, Loss:0.0000
Epoch:5684, Loss:0.0000
Epoch:5685, Loss:0.0000
Epoch:5686, Loss:0.0000
Epoch:5687, Loss:0.0000
Epoch:5688, Loss:0.0000
Epoch:5689, Loss:0.0000
Epoch:5690, Loss:0.0000
Epoch:5691, Loss:0.0000
Epoch:5692, Loss:0.0000
Epoch:5693, Loss:0.0000
Epoch:5694, Loss:0.0000
Epoch:5695, Loss:0.0000
Epoch:5696, Loss:0.0000
Epoch:5697, Loss:0.0000
Epoch:5698, Loss:0.0000
Epoch:5699, Loss:0.0000
Epoch:5700, Loss:0.0000
Epoch:5701, Loss:0.0000
Epoch:5702, Loss:0.0000
Epoch:5703, Loss:0.0000
Epoch:5704, Loss:0.0000
Epoch:5705, Loss:0.0000
Epoch:5706, Loss

Epoch:6018, Loss:0.0000
Epoch:6019, Loss:0.0000
Epoch:6020, Loss:0.0000
Epoch:6021, Loss:0.0000
Epoch:6022, Loss:0.0000
Epoch:6023, Loss:0.0000
Epoch:6024, Loss:0.0000
Epoch:6025, Loss:0.0000
Epoch:6026, Loss:0.0000
Epoch:6027, Loss:0.0000
Epoch:6028, Loss:0.0000
Epoch:6029, Loss:0.0000
Epoch:6030, Loss:0.0000
Epoch:6031, Loss:0.0000
Epoch:6032, Loss:0.0000
Epoch:6033, Loss:0.0000
Epoch:6034, Loss:0.0000
Epoch:6035, Loss:0.0000
Epoch:6036, Loss:0.0000
Epoch:6037, Loss:0.0000
Epoch:6038, Loss:0.0000
Epoch:6039, Loss:0.0000
Epoch:6040, Loss:0.0000
Epoch:6041, Loss:0.0000
Epoch:6042, Loss:0.0000
Epoch:6043, Loss:0.0000
Epoch:6044, Loss:0.0000
Epoch:6045, Loss:0.0000
Epoch:6046, Loss:0.0000
Epoch:6047, Loss:0.0000
Epoch:6048, Loss:0.0000
Epoch:6049, Loss:0.0000
Epoch:6050, Loss:0.0000
Epoch:6051, Loss:0.0000
Epoch:6052, Loss:0.0000
Epoch:6053, Loss:0.0000
Epoch:6054, Loss:0.0000
Epoch:6055, Loss:0.0000
Epoch:6056, Loss:0.0000
Epoch:6057, Loss:0.0000
Epoch:6058, Loss:0.0000
Epoch:6059, Loss

Epoch:6376, Loss:0.0000
Epoch:6377, Loss:0.0000
Epoch:6378, Loss:0.0000
Epoch:6379, Loss:0.0000
Epoch:6380, Loss:0.0000
Epoch:6381, Loss:0.0000
Epoch:6382, Loss:0.0000
Epoch:6383, Loss:0.0000
Epoch:6384, Loss:0.0000
Epoch:6385, Loss:0.0000
Epoch:6386, Loss:0.0000
Epoch:6387, Loss:0.0000
Epoch:6388, Loss:0.0000
Epoch:6389, Loss:0.0000
Epoch:6390, Loss:0.0000
Epoch:6391, Loss:0.0000
Epoch:6392, Loss:0.0000
Epoch:6393, Loss:0.0000
Epoch:6394, Loss:0.0000
Epoch:6395, Loss:0.0000
Epoch:6396, Loss:0.0000
Epoch:6397, Loss:0.0000
Epoch:6398, Loss:0.0000
Epoch:6399, Loss:0.0000
Epoch:6400, Loss:0.0000
Epoch:6401, Loss:0.0000
Epoch:6402, Loss:0.0000
Epoch:6403, Loss:0.0000
Epoch:6404, Loss:0.0000
Epoch:6405, Loss:0.0000
Epoch:6406, Loss:0.0000
Epoch:6407, Loss:0.0000
Epoch:6408, Loss:0.0000
Epoch:6409, Loss:0.0000
Epoch:6410, Loss:0.0000
Epoch:6411, Loss:0.0000
Epoch:6412, Loss:0.0000
Epoch:6413, Loss:0.0000
Epoch:6414, Loss:0.0000
Epoch:6415, Loss:0.0000
Epoch:6416, Loss:0.0000
Epoch:6417, Loss

Epoch:6736, Loss:0.0000
Epoch:6737, Loss:0.0000
Epoch:6738, Loss:0.0000
Epoch:6739, Loss:0.0000
Epoch:6740, Loss:0.0000
Epoch:6741, Loss:0.0000
Epoch:6742, Loss:0.0000
Epoch:6743, Loss:0.0000
Epoch:6744, Loss:0.0000
Epoch:6745, Loss:0.0000
Epoch:6746, Loss:0.0000
Epoch:6747, Loss:0.0000
Epoch:6748, Loss:0.0000
Epoch:6749, Loss:0.0000
Epoch:6750, Loss:0.0000
Epoch:6751, Loss:0.0000
Epoch:6752, Loss:0.0000
Epoch:6753, Loss:0.0000
Epoch:6754, Loss:0.0000
Epoch:6755, Loss:0.0000
Epoch:6756, Loss:0.0000
Epoch:6757, Loss:0.0000
Epoch:6758, Loss:0.0000
Epoch:6759, Loss:0.0000
Epoch:6760, Loss:0.0000
Epoch:6761, Loss:0.0000
Epoch:6762, Loss:0.0000
Epoch:6763, Loss:0.0000
Epoch:6764, Loss:0.0000
Epoch:6765, Loss:0.0000
Epoch:6766, Loss:0.0000
Epoch:6767, Loss:0.0000
Epoch:6768, Loss:0.0000
Epoch:6769, Loss:0.0000
Epoch:6770, Loss:0.0000
Epoch:6771, Loss:0.0000
Epoch:6772, Loss:0.0000
Epoch:6773, Loss:0.0000
Epoch:6774, Loss:0.0000
Epoch:6775, Loss:0.0000
Epoch:6776, Loss:0.0000
Epoch:6777, Loss

Epoch:7088, Loss:0.0000
Epoch:7089, Loss:0.0000
Epoch:7090, Loss:0.0000
Epoch:7091, Loss:0.0000
Epoch:7092, Loss:0.0000
Epoch:7093, Loss:0.0000
Epoch:7094, Loss:0.0000
Epoch:7095, Loss:0.0000
Epoch:7096, Loss:0.0000
Epoch:7097, Loss:0.0000
Epoch:7098, Loss:0.0000
Epoch:7099, Loss:0.0000
Epoch:7100, Loss:0.0000
Epoch:7101, Loss:0.0000
Epoch:7102, Loss:0.0000
Epoch:7103, Loss:0.0000
Epoch:7104, Loss:0.0000
Epoch:7105, Loss:0.0000
Epoch:7106, Loss:0.0000
Epoch:7107, Loss:0.0000
Epoch:7108, Loss:0.0000
Epoch:7109, Loss:0.0000
Epoch:7110, Loss:0.0000
Epoch:7111, Loss:0.0000
Epoch:7112, Loss:0.0000
Epoch:7113, Loss:0.0000
Epoch:7114, Loss:0.0000
Epoch:7115, Loss:0.0000
Epoch:7116, Loss:0.0000
Epoch:7117, Loss:0.0000
Epoch:7118, Loss:0.0000
Epoch:7119, Loss:0.0000
Epoch:7120, Loss:0.0000
Epoch:7121, Loss:0.0000
Epoch:7122, Loss:0.0000
Epoch:7123, Loss:0.0000
Epoch:7124, Loss:0.0000
Epoch:7125, Loss:0.0000
Epoch:7126, Loss:0.0000
Epoch:7127, Loss:0.0000
Epoch:7128, Loss:0.0000
Epoch:7129, Loss

Epoch:7525, Loss:0.0000
Epoch:7526, Loss:0.0000
Epoch:7527, Loss:0.0000
Epoch:7528, Loss:0.0000
Epoch:7529, Loss:0.0000
Epoch:7530, Loss:0.0000
Epoch:7531, Loss:0.0000
Epoch:7532, Loss:0.0000
Epoch:7533, Loss:0.0000
Epoch:7534, Loss:0.0000
Epoch:7535, Loss:0.0000
Epoch:7536, Loss:0.0000
Epoch:7537, Loss:0.0000
Epoch:7538, Loss:0.0000
Epoch:7539, Loss:0.0000
Epoch:7540, Loss:0.0000
Epoch:7541, Loss:0.0000
Epoch:7542, Loss:0.0000
Epoch:7543, Loss:0.0000
Epoch:7544, Loss:0.0000
Epoch:7545, Loss:0.0000
Epoch:7546, Loss:0.0000
Epoch:7547, Loss:0.0000
Epoch:7548, Loss:0.0000
Epoch:7549, Loss:0.0000
Epoch:7550, Loss:0.0000
Epoch:7551, Loss:0.0000
Epoch:7552, Loss:0.0000
Epoch:7553, Loss:0.0000
Epoch:7554, Loss:0.0000
Epoch:7555, Loss:0.0000
Epoch:7556, Loss:0.0000
Epoch:7557, Loss:0.0000
Epoch:7558, Loss:0.0000
Epoch:7559, Loss:0.0000
Epoch:7560, Loss:0.0000
Epoch:7561, Loss:0.0000
Epoch:7562, Loss:0.0000
Epoch:7563, Loss:0.0000
Epoch:7564, Loss:0.0000
Epoch:7565, Loss:0.0000
Epoch:7566, Loss

Epoch:7960, Loss:0.0000
Epoch:7961, Loss:0.0000
Epoch:7962, Loss:0.0000
Epoch:7963, Loss:0.0000
Epoch:7964, Loss:0.0000
Epoch:7965, Loss:0.0000
Epoch:7966, Loss:0.0000
Epoch:7967, Loss:0.0000
Epoch:7968, Loss:0.0000
Epoch:7969, Loss:0.0000
Epoch:7970, Loss:0.0000
Epoch:7971, Loss:0.0000
Epoch:7972, Loss:0.0000
Epoch:7973, Loss:0.0000
Epoch:7974, Loss:0.0000
Epoch:7975, Loss:0.0000
Epoch:7976, Loss:0.0000
Epoch:7977, Loss:0.0000
Epoch:7978, Loss:0.0000
Epoch:7979, Loss:0.0000
Epoch:7980, Loss:0.0000
Epoch:7981, Loss:0.0000
Epoch:7982, Loss:0.0000
Epoch:7983, Loss:0.0000
Epoch:7984, Loss:0.0000
Epoch:7985, Loss:0.0000
Epoch:7986, Loss:0.0000
Epoch:7987, Loss:0.0000
Epoch:7988, Loss:0.0000
Epoch:7989, Loss:0.0000
Epoch:7990, Loss:0.0000
Epoch:7991, Loss:0.0000
Epoch:7992, Loss:0.0000
Epoch:7993, Loss:0.0000
Epoch:7994, Loss:0.0000
Epoch:7995, Loss:0.0000
Epoch:7996, Loss:0.0000
Epoch:7997, Loss:0.0000
Epoch:7998, Loss:0.0000
Epoch:7999, Loss:0.0000
Epoch:8000, Loss:0.0000
Epoch:8001, Loss

Epoch:8401, Loss:0.0000
Epoch:8402, Loss:0.0000
Epoch:8403, Loss:0.0000
Epoch:8404, Loss:0.0000
Epoch:8405, Loss:0.0000
Epoch:8406, Loss:0.0000
Epoch:8407, Loss:0.0000
Epoch:8408, Loss:0.0000
Epoch:8409, Loss:0.0000
Epoch:8410, Loss:0.0000
Epoch:8411, Loss:0.0000
Epoch:8412, Loss:0.0000
Epoch:8413, Loss:0.0000
Epoch:8414, Loss:0.0000
Epoch:8415, Loss:0.0000
Epoch:8416, Loss:0.0000
Epoch:8417, Loss:0.0000
Epoch:8418, Loss:0.0000
Epoch:8419, Loss:0.0000
Epoch:8420, Loss:0.0000
Epoch:8421, Loss:0.0000
Epoch:8422, Loss:0.0000
Epoch:8423, Loss:0.0000
Epoch:8424, Loss:0.0000
Epoch:8425, Loss:0.0000
Epoch:8426, Loss:0.0000
Epoch:8427, Loss:0.0000
Epoch:8428, Loss:0.0000
Epoch:8429, Loss:0.0000
Epoch:8430, Loss:0.0000
Epoch:8431, Loss:0.0000
Epoch:8432, Loss:0.0000
Epoch:8433, Loss:0.0000
Epoch:8434, Loss:0.0000
Epoch:8435, Loss:0.0000
Epoch:8436, Loss:0.0000
Epoch:8437, Loss:0.0000
Epoch:8438, Loss:0.0000
Epoch:8439, Loss:0.0000
Epoch:8440, Loss:0.0000
Epoch:8441, Loss:0.0000
Epoch:8442, Loss

Epoch:8857, Loss:0.0000
Epoch:8858, Loss:0.0000
Epoch:8859, Loss:0.0000
Epoch:8860, Loss:0.0000
Epoch:8861, Loss:0.0000
Epoch:8862, Loss:0.0000
Epoch:8863, Loss:0.0000
Epoch:8864, Loss:0.0000
Epoch:8865, Loss:0.0000
Epoch:8866, Loss:0.0000
Epoch:8867, Loss:0.0000
Epoch:8868, Loss:0.0000
Epoch:8869, Loss:0.0000
Epoch:8870, Loss:0.0000
Epoch:8871, Loss:0.0000
Epoch:8872, Loss:0.0000
Epoch:8873, Loss:0.0000
Epoch:8874, Loss:0.0000
Epoch:8875, Loss:0.0000
Epoch:8876, Loss:0.0000
Epoch:8877, Loss:0.0000
Epoch:8878, Loss:0.0000
Epoch:8879, Loss:0.0000
Epoch:8880, Loss:0.0000
Epoch:8881, Loss:0.0000
Epoch:8882, Loss:0.0000
Epoch:8883, Loss:0.0000
Epoch:8884, Loss:0.0000
Epoch:8885, Loss:0.0000
Epoch:8886, Loss:0.0000
Epoch:8887, Loss:0.0000
Epoch:8888, Loss:0.0000
Epoch:8889, Loss:0.0000
Epoch:8890, Loss:0.0000
Epoch:8891, Loss:0.0000
Epoch:8892, Loss:0.0000
Epoch:8893, Loss:0.0000
Epoch:8894, Loss:0.0000
Epoch:8895, Loss:0.0000
Epoch:8896, Loss:0.0000
Epoch:8897, Loss:0.0000
Epoch:8898, Loss

Epoch:9206, Loss:0.0000
Epoch:9207, Loss:0.0000
Epoch:9208, Loss:0.0000
Epoch:9209, Loss:0.0000
Epoch:9210, Loss:0.0000
Epoch:9211, Loss:0.0000
Epoch:9212, Loss:0.0000
Epoch:9213, Loss:0.0000
Epoch:9214, Loss:0.0000
Epoch:9215, Loss:0.0000
Epoch:9216, Loss:0.0000
Epoch:9217, Loss:0.0000
Epoch:9218, Loss:0.0000
Epoch:9219, Loss:0.0000
Epoch:9220, Loss:0.0000
Epoch:9221, Loss:0.0000
Epoch:9222, Loss:0.0000
Epoch:9223, Loss:0.0000
Epoch:9224, Loss:0.0000
Epoch:9225, Loss:0.0000
Epoch:9226, Loss:0.0000
Epoch:9227, Loss:0.0000
Epoch:9228, Loss:0.0000
Epoch:9229, Loss:0.0000
Epoch:9230, Loss:0.0000
Epoch:9231, Loss:0.0000
Epoch:9232, Loss:0.0000
Epoch:9233, Loss:0.0000
Epoch:9234, Loss:0.0000
Epoch:9235, Loss:0.0000
Epoch:9236, Loss:0.0000
Epoch:9237, Loss:0.0000
Epoch:9238, Loss:0.0000
Epoch:9239, Loss:0.0000
Epoch:9240, Loss:0.0000
Epoch:9241, Loss:0.0000
Epoch:9242, Loss:0.0000
Epoch:9243, Loss:0.0000
Epoch:9244, Loss:0.0000
Epoch:9245, Loss:0.0000
Epoch:9246, Loss:0.0000
Epoch:9247, Loss

Epoch:9548, Loss:0.0000
Epoch:9549, Loss:0.0000
Epoch:9550, Loss:0.0000
Epoch:9551, Loss:0.0000
Epoch:9552, Loss:0.0000
Epoch:9553, Loss:0.0000
Epoch:9554, Loss:0.0000
Epoch:9555, Loss:0.0000
Epoch:9556, Loss:0.0000
Epoch:9557, Loss:0.0000
Epoch:9558, Loss:0.0000
Epoch:9559, Loss:0.0000
Epoch:9560, Loss:0.0000
Epoch:9561, Loss:0.0000
Epoch:9562, Loss:0.0000
Epoch:9563, Loss:0.0000
Epoch:9564, Loss:0.0000
Epoch:9565, Loss:0.0000
Epoch:9566, Loss:0.0000
Epoch:9567, Loss:0.0000
Epoch:9568, Loss:0.0000
Epoch:9569, Loss:0.0000
Epoch:9570, Loss:0.0000
Epoch:9571, Loss:0.0000
Epoch:9572, Loss:0.0000
Epoch:9573, Loss:0.0000
Epoch:9574, Loss:0.0000
Epoch:9575, Loss:0.0000
Epoch:9576, Loss:0.0000
Epoch:9577, Loss:0.0000
Epoch:9578, Loss:0.0000
Epoch:9579, Loss:0.0000
Epoch:9580, Loss:0.0000
Epoch:9581, Loss:0.0000
Epoch:9582, Loss:0.0000
Epoch:9583, Loss:0.0000
Epoch:9584, Loss:0.0000
Epoch:9585, Loss:0.0000
Epoch:9586, Loss:0.0000
Epoch:9587, Loss:0.0000
Epoch:9588, Loss:0.0000
Epoch:9589, Loss

Epoch:9968, Loss:0.0000
Epoch:9969, Loss:0.0000
Epoch:9970, Loss:0.0000
Epoch:9971, Loss:0.0000
Epoch:9972, Loss:0.0000
Epoch:9973, Loss:0.0000
Epoch:9974, Loss:0.0000
Epoch:9975, Loss:0.0000
Epoch:9976, Loss:0.0000
Epoch:9977, Loss:0.0000
Epoch:9978, Loss:0.0000
Epoch:9979, Loss:0.0000
Epoch:9980, Loss:0.0000
Epoch:9981, Loss:0.0000
Epoch:9982, Loss:0.0000
Epoch:9983, Loss:0.0000
Epoch:9984, Loss:0.0000
Epoch:9985, Loss:0.0000
Epoch:9986, Loss:0.0000
Epoch:9987, Loss:0.0000
Epoch:9988, Loss:0.0000
Epoch:9989, Loss:0.0000
Epoch:9990, Loss:0.0000
Epoch:9991, Loss:0.0000
Epoch:9992, Loss:0.0000
Epoch:9993, Loss:0.0000
Epoch:9994, Loss:0.0000
Epoch:9995, Loss:0.0000
Epoch:9996, Loss:0.0000
Epoch:9997, Loss:0.0000
Epoch:9998, Loss:0.0000
Epoch:9999, Loss:0.0000


## 6.4.1 torch和torchvision

In [34]:
import torch
from torchvision import datasets, transforms
from torch.autograd import Variable

data_train = datasets.MNIST(root = "./data/",transform=transforms,train = True,download = True)